### ISSUE TITLE
Problems 'pull' and libraries requiring org.apache.httpcomponents/httpclient !

### ISSUE THREAD

**Issue by ahoy-jon** [zcaudate/vinyasa#14]
Vinyasa/pull cannot be used with some libraries depending on certain version of org.apache.httpcomponents/httpclient.

I had problems with faraday (dynamo db client) and now I have a problem with neocons (neo4j client).

Vinyasa depends on [org.apache.httpcomponents/httpclient "4.1.2"], but other libs depends on [org.apache.httpcomponents/httpclient "4.3.2"]. Those version seems incompatible. 

Is there a solution ? 

To reproduce : 
```clojure
(./pull 'clojurewerkz/neocons)

(ns neocons.docs.examples
  (:require [clojurewerkz.neocons.rest :as nr]))

; clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to find static field: 
; CONN_MANAGER_TIMEOUT in interface org.apache.http.client.params.ClientPNames,
; compiling:;(clj_http/core.clj:137:33)
```

**Comment by expez** [comment]
@zcaudate could you make more of the functionality in `vinyasa` opt-in?  

We've tried depending on `pomegranate` in [clj-refactor](https://github.com/clojure-emacs/clj-refactor.el) (actually in the suppurting [middleware](https://github.com/clojure-emacs/refactor-nrepl))  and this has been a major source of bug reports for us.  We're getting rid of `pomegranate` in the coming days, either by using classloader isolation or by dropping the dependent functionality.

I've regretfully dropped `vinyasa` from my `profiles.clj` this morning because it's just adding too much stuff to the classpath and I don't want to spend my days debugging such issues.

**Comment by zcaudate** [comment]
Hey Lars,

I’m sorry to hear that. I for one have left out vinyasa.lein altogether and yes, I have actually faced the same problems with pomegranate. I don’t really know the solution for this, so I’ve let it slide for now.

However if you wanted to inject functionality, the project is actually split up into smaller sub-components:

if you do a search on clojars, https://clojars.org/search?q=vinyasa <https://clojars.org/search?q=vinyasa>, you will notice that there are 7 extra projects, each one is it’s own separate jar. So you can still include [im.chit/vinyasa.inject "0.3.4”] and skip the maven related ones

Hope that helps!

Chris

**Comment by expez** [comment]
@zcaudate thanks, I'll look into that!

I just replaced `pomegranate` with [alembic](https://github.com/pallet/alembic).  It was a drop-in replacement in `refactor-nrepl`.  It does its thing by loading `pomegranate` into an isolated classloader and thereby avoids causing any conflicts.

**Comment by zcaudate** [comment]
closing this issue. going with alembic as well =)
